import '../styles/reset.css';
import '../styles/globalStyles.css';
import type { Metadata } from 'next';
import Header from '@/components/layout/Header';
import localFont from 'next/font/local';
import Providers from '@/app/providers';

export const metadata: Metadata = {
  title: '김창준의 블로그',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: '../fonts/PretendardVariable.woff2',
  display: 'swap',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={pretendard.className}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
